name: Build Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle 8.7
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7

      - name: Build mod
        run: gradle build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bhopmod
          path: build/libs/
